title: About Simo
baseURL: /
params:
  description: Il Blog di simo
  color_scheme: light
  accent_color: blue
  header:
    title: About Simo
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Blog
        url: /blog/
        style: link
      - label: About
        url: /about/
        style: link
  footer:
    content: Ciao!
    has_social: true
    social_links:
      - label: Instagram
        url: 'https://www.instagram.com/'
        style: icon
        icon_class: fa-instagram
        new_window: true
      - label: Youtube
        url: lorem-ipsum
        style: icon
        icon_class: fa-youtube
        new_window: false
        type: action
      - label: Twitch
        url: lorem-ipsum
        style: icon
        icon_class: fa-twitch
        new_window: false
        type: action
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
